title: Bracca's Jellyfin
description: Media Dashboard

theme: dark
color: slate

language: en

headerStyle: clean

target: _blank

hideVersion: true

layout:
  Media:
    style: row
    columns: 2
    icon: mdi-television-play

  Clients:
    style: row
    columns: 4
    icon: mdi-cellphone-link
